### ISSUE TITLE
"Error converting signing metadata to Artifact Signer: KeyStore file not found" after upgrading to 24.6

### ISSUE THREAD

**Issue by sauliusgrigaitis** [Consensys/web3signer#1005]
`consensys/web3signer:24.2` docker image loads the keys, however `consensys/web3signer:latest` throws errors:

```
...
024-06-21 20:25:13.392+00:00 | ForkJoinPool.commonPool-worker-21 | ERROR | SignerLoader | Error converting signing metadata to Artifact Signer: KeyStore file not found: file:/opt/keys/web3signer/1.json
2024-06-21 20:25:13.392+00:00 | ForkJoinPool.commonPool-worker-1 | ERROR | SignerLoader | Error converting signing metadata to Artifact Signer: KeyStore file not found: file:/opt/keys/web3signer/2json
2024-06-21 20:25:13.392+00:00 | ForkJoinPool.commonPool-worker-9 | ERROR | SignerLoader | Error converting signing metadata to Artifact Signer: KeyStore file not found: file:/opt/keys/web3signer/3.json
...
```

**Comment by usmansaleem** [comment]
@sauliusgrigaitis Can you give the detailed docker command that you are using? It might be due to incorrect volume or file permissions, but need more details to figure out whats going wrong. Feel free to forward detailed logs to my Consensys email if privacy is a concern. `usman(dot)saleem(at)consensys.net`

**Comment by sauliusgrigaitis** [comment]
The command I run is:

`docker run -it -v "/opt/holesky/:/opt/keys" --network=host consensys/web3signer:latest --http-listen-port=19500 --key-store-path /opt/keys/holesky --http-host-allowlist "x.x.x.x" eth2 --slashing-protection-db-url="jdbc:postgresql://localhost/holeskyweb3signer" --slashing-protection-db-username=user --slashing-protection-db-password=pass --key-manager-api-enabled=true --network=holesky`

**Comment by usmansaleem** [comment]
There aren't any docker specific changes since last release (24.2.0). Can you run `ls -alh` on `/opt/holesky` on the host system? Based on the logs, it should contain `web3signer` folder. Can you also attach `ls -alh` output of at least one file under web3signer folder? The idea is to see permissions on the folder and its contents. `KeyStore file not found: file:/opt/keys/web3signer/1.json` suggests either incorrect folder/filename or permissions issues.

**Comment by usmansaleem** [comment]
Are there any further updated on this? Were you able to sort it out? @sauliusgrigaitis

**Comment by sauliusgrigaitis** [comment]
Thanks @usmansaleem , it was a permissions issue. It's weird that it worked with the older web3bigner version.
