### ISSUE TITLE
Specify `version` values for BLOCK_V2

### ISSUE THREAD

**Issue by paulhauner** [ConsenSys/web3signer#425]
Thanks for adding Altair support! Whilst implementing it for Lighthouse I had some trouble determining what the `version` value should be. Eventually I figured out it should be either:

- `PHASE0`
- `ALTAIR`

I tried modifying the docs myself to add the descriptions, but I couldn't figure out how to view the OpenAPI in my browser. I kept getting a `File not found /swagger-ui/web3signer.yaml` error.

**Comment by usmansaleem** [comment]
Hi @paulhauner ,

The source file for eth2 openapi spec is `https://github.com/ConsenSys/web3signer/blob/master/core/src/main/resources/openapi/web3signer-eth2.yaml`

Assuming you are running `gradlew assemble` to create the distribution, one of internal gradle task will bundle it in the distribution. In order to access it via web3siger, start web3signer with `--swagger-ui-enabled=true` as:
`./web3signer --http-listen-port=9000 --key-store-path=./keys -l debug --swagger-ui-enabled=true eth2 ...`

The other option is to use https://editor.swagger.io/ and paste the contents of openapi spec to get the rendering/documentation.

https://consensys.github.io/web3signer/web3signer-eth2.html to the most recent openapi spec generated and published by our CI.

Let me know if this helps.

**Comment by usmansaleem** [comment]
I am creating a PR to update OpenAPI spec to include example values for version.
