### ISSUE TITLE
ERROR: JAVA_HOME is set to an invalid directory

### ISSUE THREAD

**Issue by pablomendezroyo** [ConsenSys/web3signer#560]
**Context**
Running web3signer official docker image `consensys/web3signer:22.4.1` with the default env loaded:
```
env
HOSTNAME=25e521458948
WEB3SIGNER_METRICS_HOST=0.0.0.0
HOME=/opt/web3signer
TERM=xterm
PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
JAVA_HOME=/opt/java/openjdk
PWD=/opt/web3signer
WEB3SIGNER_HTTP_LISTEN_HOST=0.0.0.0
```

**bug**
Starting web3signer `/opt/web3signer/bin/web3signer` results in the following error:

```
ERROR: JAVA_HOME is set to an invalid directory: /opt/java/openjdk

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.
```

Where the path `/opt/java/openjdk` contains: 
```
$ pwd
/opt/java/openjdk
$ ls
bin  conf  legal  lib  release
```

**expected behaviour**
There should not be any error with the JAVA_HOME path when the environment has not been changed

**Comment by jframe** [comment]
Hi @pablomendezroyo, Can you try upgrading to the latest version of Docker this one of the breaking changes for Web3Signer 22.4.0 https://github.com/ConsenSys/web3signer/blob/master/CHANGELOG.md#breaking-changes. This issue is caused by web3signer using the latest version of Ubuntu which may mean that some version Web3Signer no longer work with older versions of docker https://bugs.launchpad.net/ubuntu/+source/libseccomp/+bug/1916485. There are also some more details in the old change log for Ubuntu https://discourse.ubuntu.com/t/hirsute-hippo-release-notes/19221.

**Comment by pablomendezroyo** [comment]
Hey! thanks for the response, I think the host should be as much agnostic as possible from the application that is running on it, especially when using docker. Having a high docker version as a requirement to run this docker image is something weird.

Is it really needed to use the latest ubuntu image? using the tag latest is something dangerous that may result in errors like this one. Docker best practices is to use a hardcoded version instead of latest.

Also, the ubuntu docker image is bigger compared to others that may be enough to run ther web3signer, such as debian-bullseye and openjdk. 

If you are agree with that, I can do a contribution updating how this docker image is created

T

**Comment by usmansaleem** [comment]
> Hey! thanks for the response, I think the host should be as much agnostic as possible from the application that is > running on it, especially when using docker. Having a high docker version as a requirement to run this docker image is something weird.

As mentioned by Jason, this is due to Ubuntu applying seccomp security features which makes it incompatible with docker daemon which doesn't have those features enabled (i.e. the older versions of podman or docker). Sooner or later, other distributions will also catch up applying these security features. It is also recommend to use latest version of docker daemon offered by the host distribution to avoid any potential security leaks/bugs.

> 
> Is it really needed to use the latest ubuntu image? using the tag latest is something dangerous that may result in errors like this one. Docker best practices is to use a hardcoded version instead of latest.

Ubuntu's latest tag point to latest LTS image which is recommend for general use. Currently it points to Ubuntu 22.04. See https://hub.docker.com/_/ubuntu. 
> 

> Also, the ubuntu docker image is bigger compared to others that may be enough to run ther web3signer, such as debian-bullseye and openjdk.
> 

In past we had used debian-slim image for Web3Signer. The main reason to switch to latest Ubuntu LTS image is due to multiple enterprise client's requirement that `docker scan` (or other scanning utilities) should not report any L1 security vulnerabilities in the base image. Ubuntu is one of the few base images that fulfill this requirement and always very quick in patching any reported security vulnerabilities as well. 

Since our dockerfile is open source, feel free to modify it according to your specific needs. At the moment Ubuntu is our preferred base image due to security considerations.

Let us know if more information is needed.
