### ISSUE TITLE
"YAMLException: The incoming YAML document exceeds the limit: 3145728 code points."

### ISSUE THREAD

**Issue by gg718** [ConsenSys/web3signer#719]
While testing PR [#692](https://github.com/ConsenSys/web3signer/pull/692), I came across the following issue with files >3MB:

> `Error parsing signing metadata file /tmp/test.yaml: YAMLException: The incoming YAML document exceeds the limit: 3145728 code points.`

Is there a reason for this limit, or can it be increased?

Ping @usmansaleem

**Comment by usmansaleem** [comment]
Hi @gg718, this "limitation" was not intended and got introduced due to underlying SnakeYaml implementation (1.32) which is used by Jackon dataformat libraries. See https://github.com/FasterXML/jackson-dataformats-text/tree/2.15/yaml#maximum-input-yaml-document-size-3-mb

We will make some modifications in Web3Signer to set the default value to 1GB and also make it configureable using a cli option as well.
